# Generated by Django 4.2.18 on 2025-02-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_fake_migration"),
        ("reviews", "0003_alter_review_product_alter_review_user"),
    ]

    operations = []
