# Generated by Django 4.2.18 on 2025-02-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_delete_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/product_images/"
            ),
        ),
    ]
