# Generated by Django 4.2.18 on 2025-02-25 17:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('SIMILAR', 'Similar Products'), ('COMPLEMENTARY', 'Frequently Bought Together'), ('UPSELL', 'Premium Alternative'), ('TRENDING', 'Trending Now')], max_length=50)),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0, 'Weight cannot be negative'), django.core.validators.MaxValueValidator(10.0, 'Weight cannot exceed 10')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='products.product')),
                ('suggested_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_for', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Suggested Items',
                'indexes': [models.Index(fields=['product', 'suggestion_type', '-weight'], name='recommendat_product_ccbf73_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='suggesteditem',
            constraint=models.UniqueConstraint(fields=('product', 'suggested_product'), name='unique_product_suggestion'),
        ),
    ]
