# Generated by Django 4.2.18 on 2025-02-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_review_options_category_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
