# Generated by Django 4.2.18 on 2025-03-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_color_product_discount_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(default="U", max_length=1),
        ),
    ]
