# Generated by Django 4.2.18 on 2025-03-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_color_alter_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
